// Generated by gencpp from file custom_msg/custom_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_CUSTOM_MSG_H
#define CUSTOM_MSG_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : x1(0.0)
    , y1(0.0)
    , z1(0.0)  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , z1(0.0)  {
  (void)_alloc;
    }



   typedef double _x1_type;
  _x1_type x1;

   typedef double _y1_type;
  _y1_type y1;

   typedef double _z1_type;
  _z1_type z1;





  typedef boost::shared_ptr< ::custom_msg::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::custom_msg::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::custom_msg::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::custom_msg::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msg': ['/home/qing/my_prj/ROS_MBOT_SIM_1/src/custom_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b905d2f7fea65b9d73ec0ad135cf49cd";
  }

  static const char* value(const ::custom_msg::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb905d2f7fea65b9dULL;
  static const uint64_t static_value2 = 0x73ec0ad135cf49cdULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/custom_msg";
  }

  static const char* value(const ::custom_msg::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x1\n\
float64 y1\n\
float64 z1\n\
";
  }

  static const char* value(const ::custom_msg::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.z1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<double>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<double>::stream(s, indent + "  ", v.y1);
    s << indent << "z1: ";
    Printer<double>::stream(s, indent + "  ", v.z1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_CUSTOM_MSG_H
